version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./storage:/app/storage
      - ./models:/app/models
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./models/llm:/root/.ollama
    ports:
      - "11434:11434"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - api